<?php
return [
            'Rural and Agriculture' => [
                "D/o Agriculture & Farmers Welfare",
                "D/o Agricultural Research and Education",
                "M/o Panchayatl Raj",
        "D/o Rural Development",
        "D/o Land Resources",
        "D/o Water Resources, River Development and Ganga Rejuvenation",
        "D/o Drinking Water and Sanitation",
        "D/o Animal Husbandry and Dairying",
        "D/o Fisheries",
        "M/o Cooperation",
        "M/o Food Processing Industnes",
        "D/o Fertilizers",
        "D/o Food and Public Distribution",
        "D/o Consumer Affarrs",
    ],

    'Infrastructure' => [
        "M/o Housing and Urban Affairs",
        "D/o Economic Affairs",
        "M/o Railways",
        "M/o Civil Aviation",
        "M/o Road Transport and Highways",
        "M/o Ports, Shipping & Waterways",
    ],

    'Resources' => [
        "M/o New and Renewable Energy",
        "M/o Power",
        "M/o Petroleum and Natural Gas",
        "M/o Environment, Forest and Climate Change",
        "M/o Coal",
        "M/o Mines",
    ],

    'Social' => [
        "D/o Youth Affairs",
        "D/o Skill Development & Entrepreneurship",
        "D/o Sports",
        "D/o Health and Family Welfare",
        "D/o Pharmaceuticals",
        "M/o AYUSH",
        "D/o Higher Education",
        "M/o Culture",
        "D/o School Education & Literacy",
    ],

    'Welfare' => [
        "M/o Women & Child Development",
        "D/o Social Justice and Empowerment",
        "M/o Tribal Affairs",
        "D/o Empowerment of Persons with Disabilities (Divyangjan)",
        "M/o Minority Affairs",
    ],

    'Finance and Economy' => [
        "D/o Expenditure",
        "D/o Economic Affairs",
        "D/o Public Enterprises",
        "NITI Aayog",
        "D/o Financial Services",
        "M/o Corporate Affairs",
        "D/o Revenue",
        "D/o Investment & Public Asset Management",
        "M/o Statistics and Programme Implementation",
    ],

    'Commerce and Industry' => [
        "D/o Commerce",
        "M/o Labour & Employment",
        "M/o Textiles",
        "M/o Heavy Industry",
        "M/o Steel",
        "M/o Tourism",
        "Department for Promotion of Industry and Internal Trade",
        "M/o Micro, Small and Medium Enterprises",
        "D/o Chemicals & Petrochemicals",
        "D/o Pharmaceuticals",
    ],

    'Technology' => [
        "D/o Telecommunications",
        "M/o Electronics and Information Technology",
        "D/o Defence Research & Development",
        "D/o Science & Technology",
        "M/o Earth Sciences",
        "D/o Agricultural Research and Education",
        "D/o Bio-Technology",
        "D/o Scientific & Industrial Research",
        "D/o Health Research",
        "M/o AYUSH",
    ],

    'Governance' => [
        "D/o Justice",
        "M/o Parliamentary Affairs",
        "D/o Official Language",
        "Legislative Department",
        "D/o Legal Affairs",
        "M/o Information and Broadcasting",
        "D/o Personnel and Training",
        "D/o Posts",
        "M/o Development of North Eastern Region",
        "D/o Administrative Reforms & PG",
        "D/o Pensions and Pensioners Welfare",
    ],

    'Security and Foreign Affairs' => [
        "D/o Defence",
        "D/o Defence Production",
        "D/o Millitary Affairs",
        "D/o Ex-Servicemen Welfare",
        "M/o Home Affairs",
        "D/o Border Management",
        "D/o Internal Security",
        "M/o External Affairs",
        "D/o Space",
        "D/o Atomic Energy",
        "D/o Defence Research & Development",
    ],
];
